### ISSUE TITLE
Cannot set itemSelected callback in element data attributes

### ISSUE THREAD

**Issue by bradoc** [tcrosen/twitter-bootstrap-typeahead#13]
This may be by design, or not even possible, but the way I generate my html and javascript it would be much cleaner to set all of the options for my typeahead in the text field's data attributes. I can set other option (like source, display) but not the callback.

This is what I want to do;

```
<input id='my_awesome_text_field' data-provide='typeahead' data-display='color' data-source='[{color:'blue'},{color:'red'},{color:'green'}]' data-itemSelected='function () {alert('itemSelected callback!')}'>
```

This is an awesome extension otherwise though - thanks!

**Comment by tcrosen** [comment]
I'm not sure how HTML5's data- API is supposed to work for callbacks.  I haven't seen any examples of functions being implemented there, and I wouldn't expect to given it is supposed to be a method of local storage, not an object.  Furthermore, as web standards gurus are arduously trying to enforce the separation of markup from styles/scripts, it definitely shouldn't be used for that purpose nor would I add extra logic to make it work that way.
