### ISSUE TITLE
twitter bootstrap typeahead 2.0.4 ajax error

### ISSUE THREAD

**Issue by ghost** [tcrosen/twitter-bootstrap-typeahead#4]
I have the following code which definitely returns a proper data result if I use the 2.0.0 version, but for some reason bootstrap's typeahead plugin is giving me an error. I pasted it below the code sample:

<input id="test" type="text" />

$('#test').typeahead({
    source: function(typeahead, query) {
        return $.post('/Profile/searchFor', { query: query }, function(data) {  
            return typeahead.process(data);
        });
    }
});
When I run this example I'm getting a jQuery bug that says the following:
Error line 104: return item.toLowerCase().indexOf(this.query.toLowerCase())

Any thoughts? ... The same code works in the 2.0.0 version of the plugin.

**Comment by tcrosen** [comment]
Is this for the original typeahead plugin via Twitter or my copy?  If it's mine, I don't officially support functions as a source (even if they did work at one point).  The latest version of my plugin offers Ajax support in the form of a custom Ajax option.  See the readme for documentation on how to use it.
