### ISSUE TITLE
crach on ajax.timerId = setTimeout

### ISSUE THREAD

**Issue by qustavo** [tcrosen/twitter-bootstrap-typeahead#6]
setTimeout crash when the argument is not a funcion or a string, in this case:

``` javascript
// Query is good to send, set a timer
this.ajax.timerId = setTimeout($.proxy(that.ajaxExecute(query), this), this.ajax.timeout);
```

so I had to do like this to fix it:

``` javascript
// Query is good to send, set a timer
this.ajax.timerId = setTimeout(function() {
    $.proxy(that.ajaxExecute(query), this)
}, this.ajax.timeout);
```

**Comment by tcrosen** [comment]
Hi gchaincl, what steps can I take to reproduce the error?

**Comment by qustavo** [comment]
it just crash, when I start using it

**Comment by tcrosen** [comment]
Can you show me your code?  It doesn't crash for me.
If you download the entire project and run the demo does it crash for you?

**Comment by qustavo** [comment]
I don't try the demos, but may be it was my fault, I was in a hurry and start monkey coding.

**Comment by tcrosen** [comment]
Ok well make sure you have the proper files included and aren't passing invalid parameters to the plugin.  If you follow the documentation and it still fails let me know.

**Comment by qustavo** [comment]
thank you very much!
