### ISSUE TITLE
Invalid argument when using AJAX

### ISSUE THREAD

**Issue by marktait** [tcrosen/twitter-bootstrap-typeahead#8]
Hi - firstly, thank you for this - it's fantastic.

I just started using the new version, however, and got the same error reported elsewhere:

I get an Invalid Argument error on this line (line 30, column 13):

```
        this.ajax.timerId = setTimeout($.proxy(that.ajaxExecute(query), this), this.ajax.timeout);
```

My script is:

```
$('.agents').typeahead({
    ajax: {url:'/api/analyst',method:'get'},
    itemSelected: displayResult
});
```

As soon as I click on Continue in VS, the drop down list briefly appears (<1sec) then disappears again (so I know the JSON is being returned).

The ajax call is returning JSON:

[{"id":4,"name":"Tait, Mark"},{"id":11,"name":"Smith, James"}.......]

Thank you for any help you may be able to provide.

Mark

**Comment by marktait** [comment]
Hi - I appear to have got the same workaround to work:

this.ajax.timerId = setTimeout(function() {
    $.proxy(that.ajaxExecute(query), this)
}, this.ajax.timeout);

I also changed:

$('.agents').typeahead({

to

$('#agents').typeahead({

And made the textbox this was associated with, have id="agents" - whereas before, I had class="agents"

I've also had problems with using the mouse to click on a selected item, in IE 9.0.8112 - the mouse click makes the dropdown disappear, but doesn't populate the textbox.  This works fine in Firefox.

Hope this helps,

thanks, Mark

**Comment by tcrosen** [comment]
Ok well I still haven't been able to reproduce the error but I added AJAX tests and the proposed workaround to 1.2.1 so hopefully the issue is gone now.
